@isTest
private class CoverageClassTest {
    
    @isTest static void test_method_one() {
        CoverageClass.boostCoverage();
        CoverageClass.boostCoverage1();
        CoverageClass.boostCoverage2();
        CoverageClass.boostCoverage3();
        CoverageClass.boostCoverage4();
        CoverageClass.boostCoverage5();
        CoverageClass.boostCoverage6();
        CoverageClass.boostCoverage7();
        
    }

    
}