public class UtilSkipTrigger{  
    public static boolean skipCheckNotificheOAS = false;
    public static boolean fromTriggerDeleteOpportunity = false;
    public static boolean skipBeforeDeleteTicket_RowTrigger = false;
    
    // Skip completo del trigger sull'Opportunity
    public static boolean skipOpportunityTrigger = false;
   
    // 03/02/2017 CA
    // Skip controllo mesi aperti
    public static boolean skipCheckIfRicaviSuMesiAperti = false;
    
}